theme: jekyll-theme-minimal
title: "WallPanel Plus"
description: "WallPanel Plus is an kiosk browser for android that is based off wallpanel, it still gets maintained unlike wallpanel!"
logo: /img/logo.png
